# Generated by Django 3.0.6 on 2020-05-10 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('position', models.TextField()),
                ('imageUrl', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('place', models.CharField(max_length=500)),
                ('teacher', models.CharField(max_length=200)),
                ('startTime', models.FloatField()),
                ('endTime', models.FloatField()),
                ('weekDay', models.IntegerField()),
                ('appointment_id', models.SlugField()),
                ('service_id', models.SlugField()),
                ('pay', models.BooleanField(default=False)),
                ('appointment', models.BooleanField()),
                ('color', models.CharField(max_length=10)),
                ('availability', models.IntegerField()),
                ('teacher_v2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.Teacher')),
            ],
        ),
    ]
