# Generated by Django 3.0.6 on 2020-05-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200511_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='imageUrl',
            field=models.SlugField(blank=True, max_length=400),
        ),
    ]
